id: P004192
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:59:48.280621
source_metadata:
  id: bdr:W2DB25428
  title: མི་དབང་རྟོགས་བརྗོད་
  author: ''
  volumes:
    ffa1ff234c47449cb0f7a2a3e56775a2:
      image_group_id: I1PD36297
      title: ''
      volume_number: 1
      total_pages: 650
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
